---
title: "Data Chats: Analytics & Politics - An Interview"
author: "Martin Chan"
date: "March 7, 2020"
output:                    # DO NOT CHANGE
  prettydoc::html_pretty:  # DO NOT CHANGE
    theme: cayman          # DO NOT CHANGE
    highlight: github      # DO NOT CHANGE
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# prettyjekyll::FormatPost("_knitr/a-beginners-guide-to-r-projects_20200123.Rmd")
```

## Background

One of the original motivations in doing these _Data Chats_ series of interviews is to speak to data and analytics practitioners from different fields and cultures, and to get a better understanding of how data is being used differently to improve our lives. The two previous interviews with [Avision Ho](https://martinctc.github.io/blog/data-chats-an-interview-with-avision-ho/) (Senior Data Scientist at the British Department for Education at the time) and [Abhishek Modi](https://martinctc.github.io/blog/data-chats-from-physics-student-to-data-science-consultant/) (Data Science Consultant at Deloitte at the time) very much focussed on the _journey_ to launching a data science career, and also on very technology-specific questions (e.g. favourite R packages). I thought I'd do an interview on a slightly different subject this time, specifically on the application of analytics for political causes.

This time, I have the pleasure of speaking with [Christopher Perera](https://worldacquire.com/christophertreshan/) and [Nanthida Rakwong](https://worldacquire.com/da/) from [Worldacquire](https://worldacquire.com/), a digital technology consultancy with politics as a core practice area. They founded the company with a mission to use technology and analytics to serve a number of different causes, including political campaigns, democratisation and human rights. Since starting the company, they have supported several campaigns, notably with the 2019 Thailand election and the 2019 Hong Kong District Council elections, where in the case of the latter they helped a pro-democracy candidate defeat a long-standing incumbent. They have also spoken at the United Nations and the UK Parliament on ethical issues in technology and society, and how to solve them.[^1]

In this interview, Christopher and Nanthida discussed their experiences in navigating between the worlds of analytics and politics, the challenges that they encountered, data ethics (e.g. Cambridge Analytica and GDPR), and more. 

[^1]: See UN-related work on digital ethics and transparency, and on anti-disinformation: https://worldacquire.com/2019/12/09/worldacquire-at-the-united-nations-igf-2019/ and https://worldacquire.com/2020/02/27/online-disinformation-and-extremism-how-it-spreads-and-how-to-stop-it/



---

## The Interview

**M: It's great to have you guys here. To start with, could you guys tell me a bit about yourselves, and what brought you to the world of analytics and politics?**

C: We set up Worldacquire almost two years ago, so we are quite a young company. Political technology consulting is one of our core strengths, and we want to help bring technology to enhance political causes such as democracy, especially in terms of applying AI and a data-driven approach. The idea is to contribute to different causes, help aspiring politicians win elections, support political parties and organisations, get a better understanding of how societies function, and support grassroot movements, all through the application of research and analytics. 

N: I was born and raised in Thailand, and moved to London in 2010. I worked with an international law firm, Amsterdam and Partners, as a political consultant. It represents many political figures from different parts of the world. I got to work with them on an important case in Thai politics - bringing the Thai military junta to justice at the International Criminal Court (ICC) for the 2010 Bangkok massacres. I worked with them for several years. During my time on the Thai project, I also worked with the pro-democracy movement in Thailand called the "Red Shirts" and other political parties in the country as well. 

C: As far as I'm concerned, I have a bit more slightly tech-y background, although I'm not a "tech-person" in the traditional sense. I started my career as a data analyst at Bloomberg in London, and then I worked for several years For most of the years after that, I worked a tech company called Viagogo, which specialised in the secondary market for tickets. There I had several roles all the way from digital marketing to global management in  overall digital advertising, product management, algorithm design, etc. As you know, many different tech roles. I moved to American Express where I was in charge of digital marketing across Europe, and my task was to bring all this expertise on algorithmic knowledge from the tech world to the 'big finance' world. At the same time, that was my last role before I founded Worldacquire. I would also mention that I've got quite a big focus on seeing tech people become more involved in ethical issues, in social issues, in fact, in 2015 I also founded Outreach Digital, which is the largest technology meet up in London, at least by now. We started entirely as, and it still currently entirely is, a pro bono community, where people meet as groups but it's entirely non-profit and community-driven. That's my background. 

**M: That sounds like a great fusion of background from politics, advertising, and tech - and bringing all these skills to deliver towards these causes. Just one thing on the meet ups - interestingly, Chris - we knew each other through one of these meet ups in London, which does show the value of these events. Just more on the background - was there any particular events or trigger points that got you thinking that wow, it would be a great idea to merge analytics and political consulting?**

N: When I worked with political parties and the grassroot movement in Thailand, basically my rule is to try and understand the situation in real-time, so that we can make better decisions. I then realised that if we can collect a lot of the data and find a way to combine the data quicker, then we can make better decisions, by which I mean - .

 That's why I'm interested in this AI technology, I know that there's a great opportunity and value to use it in a good way. Although I do see the downside in this technology as well. As you can see what happened in the UK, with Brexit, with the misuse of data, with Cambridge Analytica, and with things like that. However, my position is always that you can only advance towards a direction if you engage and participate in that world, so that was one of my motivations behind founding Worldacquire. 

**M: Just wanted to expand on that a little bit. Using AI and technology and being able to collect and combine data in real-time, or at least quicker - that helps making better decisions. Could you describe on what it was, or what is it like now in terms of general political campaigns, or how activists promote their causes? How is it done now?**

N: Let's say in the movement you have to understand millions of people. You have to find a way to understand what the majority in the movement want at that point in time. I think AI technology - by gathering the data from different sources, such as Facebook, Twitter, or some kind of forums, or even email. All this would help you understand how we can all work together to achieve the same goal. That's what it is. If you are going to run a campaign of any kind, if you don't understand what the majority of the people want, then it's very hard to get people to work together. Also, on top of that, in the campaign, you always want to find new supporters - they may be people who are unsure about your cause, or your movement, and you can use that technology to detect the people as well. Maybe the friends of your supporters, or something similar to that - they might hesitate to join your cause or your movement because they don't understand certain issues. You can then use big data to figure out what they understand, and by doing so recruit more people. 

C: To add to that particular point: one of the big things that Cambridge Analytica did was to essentially uncover a blind spot in - you can call that in business terms, the market share - but in the political world, you can call that the electorate. They literally found the people - the exact group of swing voters and targeted them with all sorts of unethical methods. Had other people been aware of this, or had everyone been aware of this kind of practice and methods, and if the communication had been more transparent as well, in terms of how we target people and what kind of messages are targeted to these people, then perhaps we wouldn't be in the current situation in the UK, right. 

So it's also a matter of using this technology for good and transparent purposes. So that's one thing. The second thing is specifically about what aspects of AI. As you know, there are many recommendation systems, there are pattern recognition techniques to find all these things, and there are many cases from AI whether they're existing products or methods that you use or combine together that can help us do our work. 

N: We use it to basically spread the truth, rather than rumours, false news. 

**M: So it's about using that responsibly, and for a good purpose - almost the opposite of what Cambridge Analytica did. Doing it in an ethical and transparent way.**

N: That's right. If you do not engage or participate in this, we're basically allowing other people in the game to misuses that, and that doesn't help. If we withdraw from this, we won't be in the right direction. [13:40]

C: Also, if you think about it, this might be more answering the motiviation side of the question. One of the practical aspects is that, in advertising in general, so when I say advertising I mean advertising on newspapers, on TV, and on billboards. It has a very long history and there has been, over the years, it has been increasingly regulated but it's still used. People use advertising to communicate with people, but it is used over time - it has become arguably more transparent, more ethical, and we believe that the same can happen for the digital space. 

**M: So it's about - not just people like not just what Cambridge Analytica did, but about engaging in that gap so that all of this is being used for a good cause. Make our democratic systems better and less prone to being abused.**

C&N: Yes, that's right. 

**M: One other interesting idea is that of the blind spot and the market share. One of the hypothesis I had was that in political campaigning, until very recently, a lot of it is invisible. You don't really know who your supporters are, and ballots are obviously secret, and political polling don't particularly have a good reputation have being accurate. So being able to look at this from multiple perspectives, and getting that transparency is pretty key.**

[16:43]

**M: Now maybe let's talk about that election project that you guys did in Thailand. Could you tell me a bit more about this?**

N: First of all, this was a long-awaited election because Thailand has been ruled by a military junta since their coup d'etat in 2014. We advised a first-time candidate from a new party standing for MP in a Bangkok constituency with 140,000 voters. Candidates were given only six weeks to campaign, which was a major challenge considering this was one of the largest constituencies.

We had no data to start with and when we went to the local administration office to request the electoral register, they basically refused to share it. We suspected this was because of the deep influence of the incumbent. Therefore we had to think differently.

We could have tried canvassing from door to door. This would have been an issue for several reasons:
Firstly, Thai people don't vote based on where they live, but on where their home was registered. Thus, people who live in a constituency may not have the right to vote.

Secondly, the political climate caused people to be wary of openly sharing their views or past voting behaviour.

The other option was to collect data and communicate online, for example through social media. Unfortunately the party leadership didn't really understand this and wasn't willing to invest in it. They wanted to play safe and spend money on leaflets and billboards.

The remaining option was a sampling method for which we used fieldwork mapping with a tool called Mela. We divided the constituency into smaller areas based on the different polling stations that cover them. We interviewed a sample of people in each area (which was still difficult, because of people's reluctance to communicate openly) and built our understanding of the overall constituency based on data.

C: I would add that we didn't do any predictive modelling or advanced AI in this instance, but this particular case really highlighted how important it is to have the right data and to make sure that the initial dataset is as clean as possible. What we often have is data scientists going online and picking whatever dataset is online - but these are often outdated, incomplete or biased. In a developing country, in particular, it is hard to verify if answers are correct, so you have to go in there and create the conditions for people to give their honest views. Once the data is accurate, you can do other things.

N: We would have certainly received more valuable insights had the party leadership approved online advertising.

C: Exactly, you cannot easily measure the conversion rate of leaflets and billboards. 

N: Especially if you only have six weeks to campaign.

C: Nonetheless we were able to run a smaller-scale test to get some online analytics data. In an ideal world we would have gathered enough data to run prediction and network algorithms to evaluate the profile, behaviour and preferences of each constituency sub-area, and thereby understand which  political issues mattered to them the most; thus, also tailor the messages that would resonate with each group. Despite not having a huge amount of data, we gathered enough to be able to draw important conclusions and insights about the people.

**M: Could you tell more about the reasons why the party leadership was reluctant to invest in social media?**

C: It was mainly about the advertising budget.

N: We did have a social media presence - everyone in Thailand does - but without proper advertising campaigns aimed towards targeted data collection. Most politicians in Thailand only engage in one-way communication and are not interested in understanding the audience.

C: When I used to work in-house in tech and  finance, I spent a lot of time with Google Ads and Facebook Ads, and one of the big lessons from the industry that also applies here is that you can create content or post stuff. You can get some data from that, for sure, but when you have tight time constraints, such as the six weeks campaigning time here, the data that you can get by doing online advertising is massively valuable as it is timely, more relevant and more accurate than anything you can get through "organic" or "earned" marketing. The same goes with building an audience in such a short time. That's simply how many digital platforms work.

Many colleagues in digital marketing will tell you that it can take several weeks or months of consistent work in order to build a robust presence, let alone reach "number one" on Google or Facebook results - unless you are really lucky and go "viral".

When you do an election campaign, when you have only six weeks, when you are a newcomer and face  powerful incumbents, it is impossible to rely on "organic" or "earned" marketing - paid advertising gives you immediate data and immediate results.

**M: It makes sense that this is more efficient when facing such time constraints. It is a shame that this in underutilized when people run election campaigns. Chris, what would you say is the biggest difference between working on digital advertising in a commercial vs a political environment?**

C: Typically in business you have a bit more flexibility in terms of what you can say. You can use promotional superlatives like "best tickets" or "best concerts". In politics people do that, too, but obviously it can be dangerous - think about the Brexit bus with the exaggerated claim about the NHS money. There will also be very different budgets, due to both internal and external factors. Businesses are often more ready to invest in advertising as it can means direct and immediate sales, whereas in politics the "sales cycle" can take much longer. 

N: In many countries, including Thailand, there's also a legal cap to how much you can spend on advertising.

C: Another issue is that the way in which digital platforms decide what content should gain most visibility depends on ranking algorithms, and one factor that influences those algorithms is pre-existing activity and performance. For example, if you want to advertise a car on Google, and you build Google Ads campaigns around the keyword "car", Google's algorithms will already know that this is something businesses want to advertise  based on historic performance data. The algorithms will also know that people click on ads after searching "car". On the contrary, if you use a word that was never used before or isn't typically associated with people clicking on ads, it can take much longer before Google will display ads for such keywords. So, there can be some delay before Google's data tells the algorithm that people will click on ads.

**M: So there's both a legal and also a search strategy aspect. Analytics-wise, are commercial and political advertising similar?**

C: There are many similarities, it's just about how you translate a concept from one field into another. In business, KPIs and metrics that determine success are formed around impressions, immediate sales, CTR and conversion rates. In politics it's more about long-term performance, probably along the lines of CLV (customer lifetime value). 
N: Having many clicks on your ad or post doesn't necessarily translate into votes. It could even be negative - think about the case of Prince Andrew!

**M: So what would you say was the number one biggest challenges in your work on the Thai election?**

N: Generally speaking the lack of accurate data, and the lack of awareness among the leadership of the importance of data - especially current data. People still think they can rely on old reports and outdated information.

**M: What was the outcome of the election campaign?**

N: We lost, although we received much more votes than expected. We also learned some important lessons; most importantly, the winning candidate was a candidate of the Future Forward Party, a new party that did invest much more on social media presence at a national level. We observed that they also used tailored, targeted advertising and A/B-testing to gather data about voter preferences.

The political party's image really helps the candidate. Like our candidate, he was also not a resident of the constituency, and yet he won. This was the very first time that anyone used social media as a key channel for data collection in an election campaign in Thailand.

C: This was indeed pioneering. Many political campaigners around the world use social media, but don't use it at an advanced level making the most of its algorithms and data-gathering capabilities.

As we mentioned several times, we had difficulties accessing data due to various reasons. So one of the bigger learnings is that, even in the face of red tape and bureaucracy, digital platforms can help you overcome hurdles in understanding your audience.

**M: Transitioning to regulation and wider ethics... could you say data is the new oil? I suppose, a valuable resource that helps our society progress?**

C: Yes, it can be. But it depends on what kind of society it will be used in. If it is used in a society with strong data protection and privacy laws, then it can be used hand-in-hand with democratic principles. If not, then it can be like a "bad oil".

Looking back in time, also the radio was the new oil at some point. Also TV was. From a regulation point of view, they also emerged amid many concerns, including about propaganda, but over time different bodies and regulations were formed to address them, such as today's ASA in the UK, and now with data and digital technologies, we have the ICO in the UK.

**M: Does GDPR play a big part in how you work, and what's your position about it? Also, when people think about applying analytics in political advertising, people are concerned about Cambridge Analytica and Brexit. Obviously you want to promote a good cause and democracy, but how would you do the same things without repeating the same mistakes?**

N: Let's start with Obama's presidential campaign. Also Obama used similar tactics, but what did he do differently? He informed people about how data would be used. So one of they key differences is transparency.

C: I think there can be some misconceptions which influence the public perception, but also that of advertisers. Some advertisers (including businesses and politicians) can see GDPR as a nuisance, too, but in fact it is an opportunity for all parties. In the same way that media regulation helped build trust in radio and TV, GDPR and other future internet or data protection laws will help increase trust in digital spaces. Once people can feel safe about the media, they will feel even more comfortable using the platforms sharing and sharing the data on it.

When people know that there is a rule of law around data, they will feel less suspicious than with dodgy websites with little information about where their data will go. At the same time, GDPR will push companies - including advertisers - to design their activities and solutions while keeping the privacy of their users in mind. This should help encourage ethical uses of this "new oil".

As a matter of fact, there will be an increasing number of new regulations that will touch upon different issues in the realm of data-driven products, most notably AI. Algorithmic bias, for instance, is one hot topic at the moment. Since AI is based on algorithms that learn from historical data, that data could reinforce existing social biases - whether it's about predicting who will be the next criminal, or who deserves a visa or insurance. How to solve this? Regulation can and needs to answer this, whether by requiring AI products to make their program code public or creating mechanisms to prevent or defeat the bias. 

N: People need to understand how software makes important decisions, once again, transparency is vital.

C: Many of the issues around algorithms and the misperceptions of AI being dangerous come down to the fact that the technical issues are not properly explained. When AI experts and advocates come together and make an effort to ensure that biases and manipulations are eliminated from these algorithms, that's when the products and solutions based on AI can be more ethical and transparent.

**M: It is right that it's important to understand where all the data people provide goes, and I believe there's also a matter of consent, which is covered by the GDPR. What I find really interesting is algorithmic bias, which is an ethical issue, but also the fact that people can correctly judge what is right and wrong only after they are educated about how the algorithm works.**

C: Exactly, and these are the areas that regulators are starting - and should be starting - to think about.

There are some groups who think that political advertising should be completely banned. Twitter went down this road and many people applauded this decision, with the main perception being that data and algorithms can be misused the way Cambridge Analytica did. However, what was ignored was the fact that all these algorithms work in a black box, are poorly understood, and that they can be changed or overridden.

For example, a recommendation system could, instead of saying "A is better than B", explain "We recommend A over B because our algorithm observed that you like x, y and z." Now, some companies may be reluctant to fully reveal their algorithms, but they could at least give an idea of how they work and what sort of outcomes could be expected, and why.
Once again, it is about transparency.

Another aspect ignored in the whole debate about political advertising is the fact that if digital platforms like Twitter ban them, newcomer politicians will struggle to gain a following or communicate with their target audience if they have a time constraint, like in the case of Thailand. So banning political ads creates huge disadvantages to people who are already disadvantaged in terms of resources.

The right approach would have been to push for more transparency - and not only on advertising algorithms, but also on the "organic" and "earned" algorithms on social media.

N: Moreover, Twitter appears not to care that much about what content is posted on the platform. If they can ban political ads, why do they do so little against hate speech and other online harms?

**M: It is also very unclear how they will actually implement the ban**

N: I find it dangerous how the CEO of Twitter Jack Dorsey calls for "earned" popularity and encourages a culture of going viral. Does a tweet that goes viral really mean that it earned it? Is it really more accurate and correct than other tweets? Sometimes a viral message can contain false accusations and fake news, too.

C: To make things worse, going viral is also determined by algorithms. How does Twitter decide which content should take the top visibility? Is it only the likes, the retweets, the popularity of the tweet author and their followers? We have seen how easily this can be manipulated.

Banning political ads doesn't solve the problem of powerful obscure algorithms, as organic content is decided by less known ones. Typically, such algorithms seem to favour users who already have a strong following - in the case of an election, this is often the incumbent. Newcomers are further penalized by this dynamic.

Another issue are fake users and bots on Twitter. These can be bought in thousands or more to exaggerate the popularity of a particular user or a post. Equally, your competitor could get 10,000 Twitter bots or fake users to report your public posts as spam or abusive. This is an easy way to manipulate the system. The Twitter algorithm will likely disregard the fact that the users are fake and make the misreported tweet disappear even if it is genuinely popular.

**M: This is something I have seen in Hong Kong, too. Do you think censorship is a solution?**

C: Did TVs ban political ads? Do billboards ban political ads? Not really, so we really don't think that banning political ads is a solution.

N: It should be more about regulating content, what is not OK to say.

**M: How do you differentiate yourselves from other consultancies or agencies that do the same or similar things as you?**

N: Firstly, aside from working on the big picture strategy we actually also implement it right on the ground. Working hands-on gives us a much more accurate picture of the real action and what kind of dynamics, limitations and issues could be faced.

C: This is a really important point, also in relation to the discussion about political ads. You will hear many academics, researchers and thought leaders jump and praise Jack Dorsey for banning political ads, but if you're a practitioner personally setting up digital campaigns for politics you will understand how disastrous that is.

So our biggest USP is that we work on the ground and have a thorough understanding of technical implementation.

**M: This ties back with what you mentioned about 'blind spots'. Being on the ground helps you spot them, correct?**

N: Correct, and it also helps with finding alternative solutions in case Plan A didn't work in the first place."

**M: What is your vision for the business?**

C: We truly believe that AI, data and digital technologies can be used for good causes - and we want to show that this is true and applies to anywhere in the world. At the same time, it is important for people to understand the uses of these technologies and the actors who control them. In essence, we want to help people understand both sides of the coin. Many governments and NGOs have them on their agendas, but often seem to have a very superficial knowledge of the technologies - we want to help there.
And we want to be involved with and lead the societal, political and ethical debates around these technologies, as well as demystify the exaggerated perceptions of danger. 

We want to be the communicators at the connecting point of all these different stakeholders who want to understand and benefit each other.

**M: Is there any advice you have for data scientists who aspire to work on political projects, political data scientists, or data scientists in general?**

C: Drawing on some of the points mentioned above, I would underline again the importance of understanding or getting the right data, knowing the sources and eliminating biases. Online datasets may be easier to obtain, but may be outdated and not real time. What were the conditions during the data collection process? What kind of limitations existed? Whether it's data from a sentiment analysis report or a simple survey, what could be wrong with the data? Could there be noise?

Also, the logic of any metrics on the dataset can be misleading. An easy example: think about GDP, a measure of economic growth. Does a growing GDP mean the country is improving and everyone is happier? Not really. If you look closer you will see that the GDP is distributed only among about 2% of the population.

Data scientists need to look carefully at the context of the collection process, for example how the responses to a survey were recorded, whether the system changed during the campaign, what the logic behind the metrics is and what kind of issues may lead to the data being wrong - especially if it was provided by reluctant journalists or human rights activsts.

It is a very useful exercise to try to build and audit your own dataset, as you don't easily know if other brands care about having a clean and unbiased dataset.

Finally, ethics is not only for philosophers, but also engineers. This will be a hot topic over the next years, and AI and data specialists will need to be able to explain to consumers and other stakeholders the different problems and solutions in algorithm-driven products.

N: In politics in particular, it is really important to also know context: who created the dataset, who financed or sponsored it, and who really controls overall character of the data that was collected.

C: Also, you should never be afraid to go out there on the field and collect the data by yourself - it can be really fun!

**M: Thank you again for your time, and for this very fascinating interview.**

---

## Endnotes

What I thought was an interesting theme (so far) is that the application of analytics is quite ubiquitous. But some of the data challenges that Nanthida and Chris raised are very real, and confirms the view that a considerable chunk of time in data analysis is spent on collecting, cleaning, and getting the data right for analysis in the first place, rather than doing the analysis itself. 

I hope you've enjoyed reading the above interview. If you would like to get in touch with Christopher and Nanthida, you may reach them through their website [here](https://Worldacquire.com). I'm also looking to do more interviews, so if you are a data / analytics practitioner and you think you have something interesting to share, please feel free to get in touch! 